### ISSUE TITLE
Wybór języków programowania

### ISSUE THREAD

**Issue by RadekJedrzejczyk** [RadekJedrzejczyk/Bicykl_Mapper#4]
Należy dokonać przeglądu języków programowania i wybrać odpowiednie dla zadania

**Comment by AgnieszkaPolowczyk** [comment]
[analiza_literatury.docx](https://github.com/user-attachments/files/17306467/analiza_literatury.docx)
notatka z przeprowadzonej analizy

**Comment by AlicjaPolowczyk** [comment]
[dokument1.docx](https://github.com/user-attachments/files/17306559/dokument1.docx)

jezyki + technologie

**Comment by RadekJedrzejczyk** [comment]
A co z pythonem?
@AlicjaPolowczyk
