### ISSUE TITLE
Wybór technologii

### ISSUE THREAD

**Issue by RadekJedrzejczyk** [RadekJedrzejczyk/Bicykl_Mapper#5]
Należy wybrać technologie, które mogą posłużyć do opracowania aplikacji.

**Comment by AlicjaPolowczyk** [comment]
[dokument1.docx](https://github.com/user-attachments/files/17306555/dokument1.docx)
 
jezyk + technologie

**Comment by RadekJedrzejczyk** [comment]
@AlicjaPolowczyk dopisz estymatę czasu na zadanie
