### ISSUE TITLE
Poszukiwanie podobnych rozwiązań.

### ISSUE THREAD

**Issue by RadekJedrzejczyk** [RadekJedrzejczyk/Bicykl_Mapper#7]
Poszukać należy rozwiązaąń podobnych do naszej aplikacji. 
Jakie funkcjonalności możemy odtworzyć?
Jakich funkcjonalności brakuje?

**Comment by AgnieszkaPolowczyk** [comment]
[Komoot.docx](https://github.com/user-attachments/files/17306664/Komoot.docx)
